#!/usr/bin/env python3
"""
ortholog_pipeline.py
====================
Pipeline for assigning human gene names to predicted proteins of
Branchiostoma lanceolatum via OrthoFinder ortholog inference.

DESCRIPTION
-----------
This script implements a four-step pipeline:
  1. Download protein FASTA files from NCBI for five reference species
  2. Run OrthoFinder to infer orthogroups across all species
  3. Download NCBI gene2refseq and gene_info files for NP_ -> gene symbol mapping
  4. Map each B. lanceolatum gene symbol to the best human ortholog gene name

INPUT
-----
  - NCBI feature table: GCF_035083965_1_klBraLanc5_hap2_feature_table.txt
  - OrthoFinder results (generated by step 2)
  - NCBI gene2refseq (downloaded by step 3)
  - NCBI Homo_sapiens.gene_info.gz (downloaded by step 3)

OUTPUT
------
  - symbol_to_human_ortholog.csv
    Columns: symbol, human_gene_name, human_protein_id, orthogroup, query_proteins

SPECIES USED
------------
  - Branchiostoma lanceolatum  GCF_035083965.1  (query)
  - Homo sapiens               GCF_000001405.40
  - Mus musculus               GCF_000001635.27
  - Danio rerio                GCF_000002035.6
  - Strongylocentrotus purpuratus GCF_000002235.5

USAGE
-----
  python ortholog_pipeline.py --step all
  python ortholog_pipeline.py --step 1   # Download proteomes
  python ortholog_pipeline.py --step 2   # Run OrthoFinder (~2h on M3 Pro)
  python ortholog_pipeline.py --step 3   # Download NCBI mapping files
  python ortholog_pipeline.py --step 4   # Final mapping

DEPENDENCIES
------------
  conda create -n orthofinder_env -c bioconda -c conda-forge \
      orthofinder python=3.10 ncbi-datasets-cli pandas biopython -y
  conda activate orthofinder_env

PLATFORM NOTES (macOS Apple Silicon)
-------------------------------------
  OrthoFinder 3.x must be launched with the full conda Python path to avoid
  conflicts with the system Python (MacPorts/Homebrew):
    /opt/anaconda3/envs/orthofinder_env/bin/python \
    /opt/anaconda3/envs/orthofinder_env/bin/orthofinder ...
  Working directory must have no spaces or special characters in the path,
  as DIAMOND fails to parse paths with brackets or spaces.

AUTHORS
-------
  Matteo Bozzo

CITATION
--------
  If you use this script, please cite:
  Emms D.M., Liu Y., Belcher L., Holmes J. & Kelly S. (2025).
    OrthoFinder. bioRxiv https://doi.org/10.1101/2025.07.15.664860
  Emms D.M. & Kelly S. (2019). OrthoFinder: phylogenetic orthology
    inference for comparative genomics. Genome Biology 20:238.
  Buchfink B., Xie C. & Huson D.H. (2015). Fast and sensitive protein
    alignment using DIAMOND. Nature Methods 12:59-60.

LICENSE
-------
  MIT License
  Copyright (c) 2026 Matteo Bozzo
  Permission is hereby granted, free of charge, to any person obtaining
  a copy of this software and associated documentation files (the
  "Software"), to deal in the Software without restriction, including
  without limitation the rights to use, copy, modify, merge, publish,
  distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so, subject to
  the following conditions:
  The above copyright notice and this permission notice shall be included
  in all copies or substantial portions of the Software.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import gzip
from pathlib import Path

import pandas as pd

# ──────────────────────────────────────────────────────────────────────────────
# CONFIGURATION
# ──────────────────────────────────────────────────────────────────────────────

FEATURE_TABLE   = "GCF_035083965_1_klBraLanc5_hap2_feature_table.txt"
WORK_DIR        = Path("orthofinder_run")
PROTEOMES_DIR   = WORK_DIR / "proteomes"
RESULTS_DIR     = Path.home() / "OrthoFinderbis" / "orthofinder_run" / "results"
GENE_INFO       = WORK_DIR / "Homo_sapiens.gene_info.gz"
GENE2REFSEQ     = WORK_DIR / "gene2refseq"
NP_MAPPING      = WORK_DIR / "human_NP_to_symbol.txt"
OUTPUT_CSV      = "symbol_to_human_ortholog.csv"

SPECIES = {
    "klBraLanc5": "GCF_035083965.1",
    "human":      "GCF_000001405.40",
    "mouse":      "GCF_000001635.27",
    "zebrafish":  "GCF_000002035.6",
    "seaurchin":  "GCF_000002235.5",
}

ORG_FAA   = PROTEOMES_DIR / "klBraLanc5.faa"
HUMAN_FAA = PROTEOMES_DIR / "human.faa"

N_THREADS = 10

GENE_INFO_URL   = "https://ftp.ncbi.nlm.nih.gov/gene/DATA/GENE_INFO/Mammalia/Homo_sapiens.gene_info.gz"
GENE2REFSEQ_URL = "https://ftp.ncbi.nlm.nih.gov/gene/DATA/gene2refseq.gz"

# ──────────────────────────────────────────────────────────────────────────────
# UTILITIES
# ──────────────────────────────────────────────────────────────────────────────

def run(cmd, check=True):
    print(f"\n$ {cmd}")
    result = subprocess.run(cmd, shell=True, text=True)
    if check and result.returncode != 0:
        print(f"[ERROR] Command exited with code {result.returncode}")
        sys.exit(result.returncode)
    return result


def require(tool):
    if shutil.which(tool) is None:
        print(f"[ERROR] '{tool}' not found in PATH.")
        sys.exit(1)


# ──────────────────────────────────────────────────────────────────────────────
# STEP 1 — Download proteomes
# ──────────────────────────────────────────────────────────────────────────────

def step1_download():
    require("datasets")
    PROTEOMES_DIR.mkdir(parents=True, exist_ok=True)

    for name, accession in SPECIES.items():
        dest_faa = PROTEOMES_DIR / f"{name}.faa"
        if dest_faa.exists():
            print(f"[SKIP] {dest_faa} already present.")
            continue

        zip_path = WORK_DIR / f"{name}.zip"
        print(f"\n[STEP 1] Downloading proteome {name} ({accession})...")
        run(f"datasets download genome accession {accession} --include protein --filename {zip_path}")
        run(f"unzip -o {zip_path} -d {WORK_DIR / name}")

        faa_candidates = list((WORK_DIR / name).glob("ncbi_dataset/data/*/protein.faa"))
        if not faa_candidates:
            print(f"[ERROR] protein.faa not found after unzip of {accession}.")
            sys.exit(1)

        shutil.copy(faa_candidates[0], dest_faa)
        print(f"[OK] Proteome saved to {dest_faa}")

    for faa in PROTEOMES_DIR.glob("*.faa"):
        n = int(subprocess.getoutput(f"grep -c '^>' {faa}"))
        print(f"  {faa.name}: {n:,} protein sequences")


# ──────────────────────────────────────────────────────────────────────────────
# STEP 2 — Run OrthoFinder
# ──────────────────────────────────────────────────────────────────────────────

def step2_orthofinder():
    existing = list(RESULTS_DIR.glob("Results_*"))
    if existing:
        print(f"[SKIP] OrthoFinder results already present in {existing[-1]}.")
        return

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    print(f"\n[STEP 2] Running OrthoFinder with {N_THREADS} threads...")
    print("  NOTE: On macOS Apple Silicon, OrthoFinder must be called with the full")
    print("  conda Python path. Adjust paths below if your conda prefix differs.")

    run(
        f"/opt/anaconda3/envs/orthofinder_env/bin/python "
        f"/opt/anaconda3/envs/orthofinder_env/bin/orthofinder "
        f"-f {PROTEOMES_DIR} "
        f"-t {N_THREADS} "
        f"-a {N_THREADS} "
        f"-S diamond "
        f"-o {RESULTS_DIR}"
    )
    print("[OK] OrthoFinder complete.")


# ──────────────────────────────────────────────────────────────────────────────
# STEP 3 — Download NCBI mapping files and build NP_ -> symbol table
# ──────────────────────────────────────────────────────────────────────────────

def step3_ncbi():
    # 3a. gene_info
    if not GENE_INFO.exists():
        print(f"\n[STEP 3a] Downloading Homo_sapiens.gene_info.gz...")
        run(f"curl -L '{GENE_INFO_URL}' -o {GENE_INFO}")
    else:
        print(f"[SKIP] {GENE_INFO} already present.")

    # 3b. gene2refseq
    gene2refseq_gz = WORK_DIR / "gene2refseq.gz"
    if not GENE2REFSEQ.exists():
        if not gene2refseq_gz.exists():
            print(f"\n[STEP 3b] Downloading gene2refseq.gz (~2GB)...")
            run(f"curl -L '{GENE2REFSEQ_URL}' -o {gene2refseq_gz}")
        print(f"\n[STEP 3b] Decompressing gene2refseq.gz...")
        print("  NOTE: On macOS, decompress before filtering (pipe fails silently).")
        run(f"gzip -d {gene2refseq_gz}")
    else:
        print(f"[SKIP] {GENE2REFSEQ} already present.")

    # 3c. Build NP_ -> symbol mapping
    if NP_MAPPING.exists() and NP_MAPPING.stat().st_size > 1000:
        print(f"[SKIP] {NP_MAPPING} already present.")
        return

    print(f"\n[STEP 3c] Building NP_ -> symbol mapping...")

    geneid_to_symbol = {}
    with gzip.open(GENE_INFO, "rt") as f:
        for line in f:
            if line.startswith("#"):
                continue
            parts = line.strip().split("\t")
            if len(parts) >= 3:
                geneid_to_symbol[parts[1]] = parts[2]

    print(f"  Human GeneIDs loaded: {len(geneid_to_symbol):,}")

    count = 0
    with open(GENE2REFSEQ, "r") as fin, open(NP_MAPPING, "w") as fout:
        for i, line in enumerate(fin):
            if i == 0:
                continue
            if i % 1_000_000 == 0:
                print(f"  Rows processed: {i:,}...")
            parts = line.split("\t")
            if len(parts) < 6:
                continue
            tax_id = parts[0]
            geneid = parts[1]
            np_acc = parts[5]
            if tax_id != "9606" or not np_acc.startswith("NP_"):
                continue
            symbol = geneid_to_symbol.get(geneid)
            if symbol:
                fout.write(f"{np_acc}\t{symbol}\n")
                count += 1

    print(f"[OK] Written {count:,} NP_ -> symbol pairs to {NP_MAPPING}")


# ──────────────────────────────────────────────────────────────────────────────
# STEP 4 — Final mapping: B. lanceolatum symbol -> human gene name
# ──────────────────────────────────────────────────────────────────────────────

def step4_mapping():
    print(f"\n[STEP 4] Mapping symbol -> human ortholog...")

    # 4a. Read feature table
    print("  Reading feature table...")
    ft = pd.read_csv(FEATURE_TABLE, sep="\t", low_memory=False, dtype=str)
    ft.columns = ft.columns.str.strip()
    feature_col = [c for c in ft.columns if "feature" in c.lower()][0]

    cds = ft[ft[feature_col] == "CDS"][["symbol", "product_accession"]].dropna()
    cds = cds[cds["product_accession"].str.startswith("XP_", na=False)]

    symbol_to_xp = (
        cds.groupby("symbol")["product_accession"]
        .apply(lambda x: list(x.unique()))
        .reset_index()
        .rename(columns={"product_accession": "query_proteins"})
    )
    print(f"  Protein-coding genes in feature table: {len(symbol_to_xp):,}")

    # 4b. Find OrthoFinder results
    results_candidates = sorted(RESULTS_DIR.glob("Results_*/"))
    if not results_candidates:
        print("[ERROR] No OrthoFinder results found. Run step 2 first.")
        sys.exit(1)

    ortho_dir = results_candidates[-1]
    print(f"  OrthoFinder results: {ortho_dir}")

    # 4c. Load Orthologues (OrthoFinder 3.x format)
    org_stem   = ORG_FAA.stem    # "klBraLanc5"
    human_stem = HUMAN_FAA.stem  # "human"

    ortho_file = ortho_dir / "Orthologues" / f"{org_stem}.tsv"
    if not ortho_file.exists():
        ortho_file = ortho_dir / "Orthologues" / f"{human_stem}.tsv"
        if not ortho_file.exists():
            print("[ERROR] Orthologues file not found.")
            for f in (ortho_dir / "Orthologues").glob("*.tsv"):
                print(f"  {f.name}")
            sys.exit(1)

    print(f"  Loading: {ortho_file.name}")
    ortho = pd.read_csv(ortho_file, sep="\t", dtype=str)

    # OrthoFinder 3.x format: Orthogroup | Species | <org_proteins> | Orthologs
    ortho = ortho[ortho["Species"] == "human"].copy()
    ortho = ortho.rename(columns={org_stem: "query_protein", "Orthologs": "human_protein"})
    ortho["query_protein"] = ortho["query_protein"].str.split(", ")
    ortho["human_protein"] = ortho["human_protein"].str.split(", ")
    ortho = ortho.explode("query_protein").explode("human_protein")
    ortho = ortho[["Orthogroup", "query_protein", "human_protein"]].dropna()
    print(f"  Ortholog pairs found: {len(ortho):,}")

    # 4d. Load NP_ -> symbol mapping
    if not NP_MAPPING.exists() or NP_MAPPING.stat().st_size == 0:
        print("[ERROR] NP_ mapping file not found. Run step 3 first.")
        sys.exit(1)

    print("  Loading NP_ -> symbol mapping...")
    np_to_symbol = {}
    with open(NP_MAPPING) as f:
        for line in f:
            parts = line.strip().split("\t")
            if len(parts) == 2:
                np_acc = parts[0].strip()
                symbol = parts[1].strip()
                np_nov = re.sub(r"\.\d+$", "", np_acc)
                np_to_symbol[np_acc] = symbol
                np_to_symbol[np_nov] = symbol

    print(f"  NP_ accessions in mapping: {len(np_to_symbol):,}")

    # 4e. Build XP_query -> best human symbol dictionary
    query_to_human = {}
    for _, row in ortho.iterrows():
        qp     = str(row["query_protein"]).strip()
        hp     = str(row["human_protein"]).strip()
        hp_nov = re.sub(r"\.\d+$", "", hp)

        human_sym = np_to_symbol.get(hp) or np_to_symbol.get(hp_nov)
        if qp not in query_to_human and human_sym:
            query_to_human[qp] = (human_sym, hp, row["Orthogroup"])

    print(f"  Query proteins with human ortholog: {len(query_to_human):,}")

    # 4f. Map symbol -> human gene name
    records = []
    for _, row in symbol_to_xp.iterrows():
        symbol     = row["symbol"]
        xp_list    = row["query_proteins"]
        human_sym  = None
        human_prot = None
        orthogroup = None

        for xp in xp_list:
            xp_nov = re.sub(r"\.\d+$", "", xp)
            hit = query_to_human.get(xp) or query_to_human.get(xp_nov)
            if hit:
                human_sym, human_prot, orthogroup = hit
                break

        records.append({
            "symbol":           symbol,
            "human_gene_name":  human_sym,
            "human_protein_id": human_prot,
            "orthogroup":       orthogroup,
            "query_proteins":   ", ".join(xp_list),
        })

    result = pd.DataFrame(records)
    n_mapped   = result["human_gene_name"].notna().sum()
    n_unmapped = result["human_gene_name"].isna().sum()

    print(f"\n  Genes with human ortholog : {n_mapped:,} ({n_mapped/len(result)*100:.1f}%)")
    print(f"  Genes without ortholog    : {n_unmapped:,} ({n_unmapped/len(result)*100:.1f}%)")
    print(f"  Total                     : {len(result):,}")

    result.to_csv(OUTPUT_CSV, index=False)
    print(f"\n[OK] Output saved to: {OUTPUT_CSV}")

    print("\n-- Preview: first 20 rows with ortholog --")
    print(result[result["human_gene_name"].notna()].head(20).to_string(index=False))

    print("\n-- Top 10 most frequent human orthologs --")
    print(result["human_gene_name"].value_counts().head(10).to_string())


# ──────────────────────────────────────────────────────────────────────────────
# ENTRY POINT
# ──────────────────────────────────────────────────────────────────────────────

STEPS = {
    "1": ("Download proteomes",            step1_download),
    "2": ("Run OrthoFinder",               step2_orthofinder),
    "3": ("Download NCBI gene files",      step3_ncbi),
    "4": ("Map symbol -> human ortholog",  step4_mapping),
}


def main():
    parser = argparse.ArgumentParser(
        description="OrthoFinder pipeline: B. lanceolatum symbol -> human gene name"
    )
    parser.add_argument(
        "--step", default="all",
        choices=list(STEPS.keys()) + ["all"],
        help="Which step to run (default: all)"
    )
    args = parser.parse_args()

    steps_to_run = list(STEPS.keys()) if args.step == "all" else [args.step]

    for s in steps_to_run:
        label, func = STEPS[s]
        print(f"\n{'='*60}")
        print(f" STEP {s}: {label}")
        print(f"{'='*60}")
        func()

    print("\n[PIPELINE COMPLETE]")


if __name__ == "__main__":
    main()
